name: Build and Deploy Jekyll


on:
push:
branches: [ main ]


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Setup Node.js
uses: actions/setup-node@v4
with:
node-version: '20'
- name: Install Tailwind
run: npm ci
- name: Build Tailwind CSS
run: npm run build:css
- name: Setup Ruby for Jekyll
uses: ruby/setup-ruby@v1
with:
ruby-version: '3.1'
- name: Install Jekyll
run: gem install bundler jekyll
- name: Build site
run: jekyll build -d ./_site
- name: Deploy to GitHub Pages
uses: peaceiris/actions-gh-pages@v4
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
publish_dir: ./_site
